name: Upload MSI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
      
      - name: Upload MSI
      - uses: actions/upload-artifact@v4
        with:
          name: Explr-Windows
          path: target/release/bundle/msi/*.msi

      - name: Install dependencies
        run: npm install

      - name: Update Cargo
        run: cargo update

      - name: Build
        run: npx tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FileExplorer
          path: target/release/bundle/msi/Explr_0.2.3_x64_en-US.msi
